# Usar la imagen oficial de PostgreSQL 16
FROM postgres:16


# Exponer el puerto por defecto de PostgreSQL
EXPOSE 5432

# Crear un volumen para persistir los datos de PostgreSQL
VOLUME ["/var/lib/postgresql/data"]

# El comando por defecto ya está definido en la imagen base
# pero se puede personalizar si es necesario
# CMD ["postgres"]

